### ISSUE TITLE
GRPCの接続に関して学ぶ

### ISSUE THREAD

**Issue by TakakiAraki09** [TakakiAraki09/zen#2]
## TODO

- [ ] Unary RPC
- [ ] Server streaming RPC
- [ ] Client streaming RPC
- [ ] Bidirectional streaming RPC
